name: test
on: [push, pull_request]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.87.0
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --all-features
  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.87.0
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy
